(ns hive-build.boundary.archive-test
  (:require [clojure.java.io :as io]
            [clojure.test :refer [deftest is testing]]
            [clojure.tools.build.api :as b]
            [hive-build.boundary.archive :as archive])
  (:import (java.nio.file Files)
           (java.nio.file.attribute FileAttribute)
           (java.util.zip ZipEntry ZipOutputStream)))

(defn- temp-dir []
  (str (Files/createTempDirectory "hive-build-test" (make-array FileAttribute 0))))

(defn- write-raw-zip!
  "A zip written the way a build tool writes one: in the order given, with the
   timestamps given."
  [path entries]
  (io/make-parents path)
  (with-open [out (ZipOutputStream. (io/output-stream path))]
    (doseq [[entry-name content time] entries]
      (.putNextEntry out (doto (ZipEntry. ^String entry-name) (.setTime (long time))))
      (.write out (.getBytes ^String content "UTF-8"))
      (.closeEntry out)))
  path)

(defn- bytes-of [path]
  (seq (Files/readAllBytes (.toPath (io/file path)))))

(def fixture-source
  "(ns s0.fixture)\n(defn secret \"S0-DOCSTRING-MARKER\" [x] (+ x 1))\n")

(defn- fixture-layout [root]
  {:root root
   :src-dir (str root "/src")
   :class-dir (str root "/classes")
   :jar-file (str root "/fixture.jar")})

(defn- compile-fixture!
  [{:keys [src-dir class-dir]} elide-meta]
  (let [source (io/file src-dir "s0/fixture.clj")
        basis (b/create-basis {:project "deps.edn" :extra {:paths [src-dir]}})]
    (io/make-parents source)
    (spit source fixture-source)
    (b/compile-clj
     (cond-> {:basis basis
              :src-dirs [src-dir]
              :ns-compile ['s0.fixture]
              :class-dir class-dir}
       elide-meta (assoc :compile-opts {:elide-meta elide-meta})))
    basis))

(defn- init-class-text [{:keys [class-dir]}]
  (String. ^bytes (Files/readAllBytes
                   (.toPath (io/file class-dir "s0/fixture__init.class")))
           "ISO-8859-1"))

(defn- build-raw-fixture-jar!
  [{:keys [class-dir jar-file src-dir] :as layout}]
  (b/delete {:path class-dir})
  (let [basis (compile-fixture! layout [:doc :file :line :added :arglists])]
    (b/write-pom {:class-dir class-dir
                  :lib 's0/fixture
                  :version "1.0.0"
                  :basis basis
                  :src-dirs [src-dir]})
    (b/jar {:class-dir class-dir :jar-file jar-file})
    jar-file))

(defn- await-next-wall-clock-second! []
  (let [second (quot (System/currentTimeMillis) 1000)]
    (loop []
      (when (= second (quot (System/currentTimeMillis) 1000))
        (Thread/sleep 10)
        (recur)))))

(def sample
  [["b/second.clj" "(ns b.second)" 1700000000000]
   ["a/first.clj" "(ns a.first)" 1600000000000]
   ["META-INF/MANIFEST.MF" "Manifest-Version: 1.0" 1500000000000]])

(deftest entries-round-trip-through-a-zip
  (let [path (str (temp-dir) "/x.jar")]
    (write-raw-zip! path sample)
    (let [read-back (archive/entries path)]
      (is (= #{"a/first.clj" "b/second.clj" "META-INF/MANIFEST.MF"} (set (keys read-back))))
      (is (= "(ns a.first)" (String. ^bytes (get read-back "a/first.clj") "UTF-8"))))))

(deftest entries-are-returned-in-name-order
  (let [path (str (temp-dir) "/x.jar")]
    (write-raw-zip! path sample)
    (is (= ["META-INF/MANIFEST.MF" "a/first.clj" "b/second.clj"]
           (keys (archive/entries path))))))

(deftest two-builds-of-identical-content-are-byte-identical
  (testing "the contract the whole attribution story rests on: any difference
            between two copies of an artifact is content"
    (let [dir (temp-dir)
          one (str dir "/one.jar")
          two (str dir "/two.jar")]
      ;; Same content, written in a different order with different timestamps —
      ;; exactly what two runs of a build on two machines produce.
      (write-raw-zip! one sample)
      (write-raw-zip! two (map (fn [[n c _]] [n c (System/currentTimeMillis)])
                               (reverse sample)))
      (is (not= (bytes-of one) (bytes-of two)) "the fixture must start out different")
      (archive/normalize-jar! one)
      (archive/normalize-jar! two)
      (is (= (bytes-of one) (bytes-of two))))))

(deftest a-timestamp-written-into-entry-content-is-normalized-too
  (testing "tools.build stamps the wall clock INSIDE pom.properties, where a
            ZIP timestamp rewrite cannot reach it. Fixing entry times alone
            left every jar different from every other."
    (let [dir (temp-dir)
          one (str dir "/one.jar")
          two (str dir "/two.jar")
          properties (fn [stamp]
                       [["META-INF/maven/g/a/pom.properties"
                         (str "# Generated by org.clojure/tools.build\n"
                              "# " stamp "\n"
                              "version=1.0.0\ngroupId=g\nartifactId=a")
                         0]
                        ["META-INF/MANIFEST.MF"
                         "Manifest-Version: 1.0\nBuild-Jdk-Spec: 26\n"
                         0]
                        ["a/first.clj" "(ns a.first)" 0]])]
      (write-raw-zip! one (properties "Sat Aug 8 03:55:39 UTC 2026"))
      (write-raw-zip! two (properties "Sat Aug 8 03:55:44 UTC 2026"))
      (is (not= (bytes-of one) (bytes-of two)) "the fixture must start out different")
      (archive/normalize-jar! one)
      (archive/normalize-jar! two)
      (is (= (bytes-of one) (bytes-of two))))))

(deftest a-jar-built-under-a-different-jdk-is-still-identical
  (testing "reproducible on one machine and nowhere else is the case that
            matters least"
    (let [dir (temp-dir)
          one (str dir "/one.jar")
          two (str dir "/two.jar")
          with-jdk (fn [jdk]
                     [["META-INF/MANIFEST.MF"
                       (str "Manifest-Version: 1.0\nBuild-Jdk-Spec: " jdk "\n")
                       0]
                      ["a/first.clj" "(ns a.first)" 0]])]
      (write-raw-zip! one (with-jdk "21"))
      (write-raw-zip! two (with-jdk "26"))
      (archive/normalize-jar! one)
      (archive/normalize-jar! two)
      (is (= (bytes-of one) (bytes-of two))))))

(deftest real-builds-distinguish-elision-on-from-off
  (testing "compile actual Clojure: a captured option map cannot prove elision"
    (let [dir (temp-dir)
          on (fixture-layout (str dir "/on"))
          off (fixture-layout (str dir "/off"))]
      (compile-fixture! on [:doc :file :line :added :arglists])
      (compile-fixture! off nil)
      (let [elided (init-class-text on)
            control (init-class-text off)]
        (is (not (.contains elided "S0-DOCSTRING-MARKER")))
        (is (not (.contains elided "arglists")))
        (is (.contains control "S0-DOCSTRING-MARKER"))
        (is (.contains control "arglists"))))))

(deftest two-real-builds-normalize-to-identical-jars
  (testing "run compile, write-pom and jar twice; prove the control differs"
    (let [dir (temp-dir)
          layout (fixture-layout (str dir "/build"))
          first (str dir "/first.jar")
          second (str dir "/second.jar")]
      (io/copy (io/file (build-raw-fixture-jar! layout)) (io/file first))
      (await-next-wall-clock-second!)
      (io/copy (io/file (build-raw-fixture-jar! layout)) (io/file second))
      (is (not= (bytes-of first) (bytes-of second))
          "the two real tools.build outputs must differ before normalization")
      (archive/normalize-jar! first)
      (archive/normalize-jar! second)
      (is (= (bytes-of first) (bytes-of second))))))

(deftest normalization-never-decodes-binary-content
  (testing "a class file passed through a text rewrite would be corrupted"
    (let [path (str (temp-dir) "/x.jar")
          raw (byte-array (map unchecked-byte [0xCA 0xFE 0xBA 0xBE 0x00 0xFF 0x80 0x7F]))]
      (io/make-parents path)
      (with-open [out (ZipOutputStream. (io/output-stream path))]
        (.putNextEntry out (ZipEntry. "a/Klass.class"))
        (.write out raw)
        (.closeEntry out))
      (archive/normalize-jar! path)
      (is (= (seq raw) (seq (get (archive/entries path) "a/Klass.class")))))))

(deftest normalization-is-idempotent
  (let [path (str (temp-dir) "/x.jar")]
    (write-raw-zip! path sample)
    (archive/normalize-jar! path)
    (let [once (bytes-of path)]
      (archive/normalize-jar! path)
      (is (= once (bytes-of path))))))

(deftest normalization-preserves-content
  (let [path (str (temp-dir) "/x.jar")]
    (write-raw-zip! path sample)
    (let [before (archive/entries path)]
      (archive/normalize-jar! path)
      (let [after (archive/entries path)]
        (is (= (keys before) (keys after)))
        (is (every? (fn [k] (= (seq (get before k)) (seq (get after k)))) (keys before)))))))

(deftest a-content-difference-survives-normalization
  (testing "normalization erases timestamps, never bytes: two artifacts that
            differ in content must still differ afterwards"
    (let [dir (temp-dir)
          one (str dir "/one.jar")
          two (str dir "/two.jar")
          personalized (mapv (fn [[n c t]]
                               (if (= "a/first.clj" n)
                                 [n (str c " ;; personalized") t]
                                 [n c t]))
                             sample)]
      (write-raw-zip! one sample)
      (write-raw-zip! two personalized)
      (archive/normalize-jar! one)
      (archive/normalize-jar! two)
      (is (not= (bytes-of one) (bytes-of two))))))

(deftest normalization-leaves-no-temporary-behind
  (let [path (str (temp-dir) "/x.jar")]
    (write-raw-zip! path sample)
    (archive/normalize-jar! path)
    (is (not (.exists (io/file (str path ".norm")))))))

;; ── Selective extraction ──────────────────────────────────────────────────

(defn- touch! [path]
  (io/make-parents path)
  (spit path "class-bytes")
  path)

(deftest only-this-projects-classes-are-copied-out
  (let [dir (temp-dir)
        from (str dir "/aot-classes")
        to (str dir "/classes")]
    (touch! (str from "/hive_thing/core__init.class"))
    (touch! (str from "/hive_thing/core$fn__1.class"))
    (touch! (str from "/host_lib/protocol__init.class"))
    (touch! (str from "/host_lib/IHost.class"))
    (touch! (str from "/hive_thing/core.clj"))
    (let [copied (archive/copy-own-classes! from to ["hive_thing/core"]
                                            ["host_lib/IHost.class"])]
      (is (= #{"hive_thing/core__init.class" "hive_thing/core$fn__1.class"
               "host_lib/IHost.class"}
             (set copied)))
      (is (.exists (io/file to "hive_thing/core__init.class")))
      (is (.exists (io/file to "host_lib/IHost.class")))
      (testing "the preloaded host class stays behind"
        (is (not (.exists (io/file to "host_lib/protocol__init.class")))))
      (testing "and so does the source that was compiled"
        (is (not (.exists (io/file to "hive_thing/core.clj"))))))))

(deftest copying-with-no-prefixes-copies-nothing
  (let [dir (temp-dir)
        from (str dir "/aot-classes")
        to (str dir "/classes")]
    (touch! (str from "/hive_thing/core__init.class"))
    (is (= [] (archive/copy-own-classes! from to [])))
    (is (not (.exists (io/file to))))))
