(ns hive-build.promote.reproducible-test
  (:require [clojure.string :as str]
            [clojure.test :refer [deftest is testing]]
            [clojure.test.check.clojure-test :as tc]
            [clojure.test.check.generators :as gen]
            [clojure.test.check.properties :as prop]
            [hive-build.promote.reproducible :as repro]))

(def pom-properties
  (str "# Generated by org.clojure/tools.build\n"
       "# Sat Aug 8 03:55:39 UTC 2026\n"
       "version=0.1.0\n"
       "groupId=io.github.hive-agi\n"
       "artifactId=hive-build"))

(def manifest
  (str "Manifest-Version: 1.0\n"
       "Created-By: org.clojure/tools.build\n"
       "Build-Jdk-Spec: 26\n"))

;; ── The two sources of variance, named ────────────────────────────────────

(deftest a-maven-timestamp-comment-is-removed
  (testing "the wall clock tools.build stamps into pom.properties is why two
            builds seconds apart produced different bytes"
    (is (= (str "version=0.1.0\n"
                "groupId=io.github.hive-agi\n"
                "artifactId=hive-build")
           (repro/normalize-text "META-INF/maven/g/a/pom.properties" pom-properties)))))

(deftest the-properties-that-carry-meaning-survive
  (let [out (repro/normalize-text "pom.properties" pom-properties)]
    (doseq [line ["version=0.1.0" "groupId=io.github.hive-agi" "artifactId=hive-build"]]
      (is (str/includes? out line)))))

(deftest the-build-jdk-is-removed-from-the-manifest
  (testing "keeping it makes an artifact reproducible on one machine and
            nowhere else, which is the case that matters least"
    (let [out (repro/normalize-text "META-INF/MANIFEST.MF" manifest)]
      (is (not (str/includes? out "Build-Jdk-Spec")))
      (is (str/includes? out "Manifest-Version: 1.0"))
      (is (str/includes? out "Created-By: org.clojure/tools.build")))))

(deftest a-rewritten-manifest-is-still-a-manifest
  (testing "the JAR specification requires the main section to end with a
            newline, and split-lines drops it"
    (let [out (repro/normalize-text "META-INF/MANIFEST.MF" manifest)]
      (is (str/ends-with? out "\n"))
      (let [parsed (java.util.jar.Manifest.
                    (java.io.ByteArrayInputStream. (.getBytes out "UTF-8")))]
        (is (= "1.0" (.getValue (.getMainAttributes parsed) "Manifest-Version")))
        (is (= "org.clojure/tools.build"
               (.getValue (.getMainAttributes parsed) "Created-By")))
        (is (nil? (.getValue (.getMainAttributes parsed) "Build-Jdk-Spec")))))))

(deftest a-file-without-a-trailing-newline-does-not-gain-one
  (is (not (str/ends-with? (repro/normalize-text "pom.properties" pom-properties) "\n"))))

(deftest line-structure-is-preserved-exactly
  (testing "clojure.string/split-lines discards trailing empty lines, so a
            naive split/join loses the newline the JAR spec requires and makes
            rewriting twice disagree with rewriting once"
    (is (= "a\n\n" (repro/strip-comments "a\n\n")))
    (is (= "a\n\n" (repro/strip-comments "# c\na\n\n")))
    (is (= "\n" (repro/strip-comments "\n")))
    (is (= "" (repro/strip-comments "")))
    (is (= "a\n\n" (repro/drop-headers ["X"] "X: 1\na\n\n")))))

;; ── Which entries are touched at all ──────────────────────────────────────

(deftest only-the-claimed-entries-are-touched
  (testing "a class file must never be decoded as text"
    (is (repro/nondeterministic? "META-INF/maven/g/a/pom.properties"))
    (is (repro/nondeterministic? "META-INF/MANIFEST.MF"))
    (is (not (repro/nondeterministic? "hive_build/api__init.class")))
    (is (not (repro/nondeterministic? "hive_build/api.clj")))
    (is (not (repro/nondeterministic? "META-INF/maven/g/a/pom.xml")))
    (is (not (repro/nondeterministic? "logo.png")))))

(deftest an-unclaimed-entry-passes-through-unchanged
  (let [text "(ns hive-build.api)\n;; # not a comment line in a properties sense\n"]
    (is (= text (repro/normalize-text "hive_build/api.clj" text)))))

;; ── Properties ────────────────────────────────────────────────────────────

(tc/defspec normalization-is-idempotent 200
  (prop/for-all [entry-name (gen/elements ["META-INF/MANIFEST.MF"
                                           "META-INF/maven/g/a/pom.properties"
                                           "hive_build/api.clj"])
                 lines (gen/vector (gen/elements ["# a comment"
                                                  "Build-Jdk-Spec: 26"
                                                  "version=1.0.0"
                                                  "Manifest-Version: 1.0"
                                                  ""])
                                   0 8)]
    (let [text (str/join "\n" lines)
          once (repro/normalize-text entry-name text)]
      (= once (repro/normalize-text entry-name once)))))

(tc/defspec normalization-never-adds-a-line 200
  (prop/for-all [entry-name (gen/elements ["META-INF/MANIFEST.MF"
                                           "META-INF/maven/g/a/pom.properties"
                                           "hive_build/api.clj"])
                 lines (gen/vector (gen/elements ["# c" "Build-Jdk-Spec: 26" "k=v" ""]) 0 8)]
    (let [text (str/join "\n" lines)]
      (<= (count (str/split-lines (repro/normalize-text entry-name text)))
          (count (str/split-lines text))))))

(deftest stripping-comments-leaves-everything-else
  (is (= "a=1\nb=2" (repro/strip-comments "# x\na=1\n#y\nb=2")))
  (is (= "" (repro/strip-comments "# only comments\n# here")))
  (is (= "a=1" (repro/strip-comments "a=1"))))

(deftest dropping-headers-matches-the-whole-name
  (testing "a header whose name merely starts with another must survive"
    (is (= "Build-Jdk-Spec-Extra: x"
           (repro/drop-headers ["Build-Jdk"] "Build-Jdk-Spec-Extra: x")))
    (is (= "" (repro/drop-headers ["Build-Jdk-Spec-Extra"] "Build-Jdk-Spec-Extra: x")))))

;; ── Open for extension ────────────────────────────────────────────────────

(deftest a-newly-found-source-of-variance-is-an-addition
  (let [git-props (reify repro/IEntryRule
                    (rule-id [_] :git-properties)
                    (applies? [_ entry-name] (= "git.properties" entry-name))
                    (rewrite [_ text] (repro/strip-comments text)))
        rules (conj repro/default-rules git-props)]
    (is (not (repro/nondeterministic? "git.properties")))
    (is (repro/nondeterministic? rules "git.properties"))
    (is (= "sha=abc" (repro/normalize-text rules "git.properties" "# built now\nsha=abc")))
    (testing "and changes nothing about the existing rules"
      (is (= (repro/normalize-text "pom.properties" pom-properties)
             (repro/normalize-text rules "pom.properties" pom-properties))))))

(deftest every-default-rule-has-a-distinct-id
  (let [ids (map repro/rule-id repro/default-rules)]
    (is (= (count ids) (count (distinct ids))))
    (is (= #{:maven-pom-properties :jar-manifest} (set ids)))))
