(ns hive-build.promote.changelog
  "A CHANGELOG.md, rendered from release notes. Pure.

   Keep a Changelog 1.1.0 shape over the Note value defined by
   `hive-build.promote.notes`, so the file and the storefront show one
   derivation of the same commits rather than two accounts of them.

   The generated document is disposable: every release rewrites it in full.
   The prose a generator cannot derive (what the version number promises, how
   to migrate off a break, a deprecation window) is authored in
   `changelog.d/<version>.md` and spliced in here, never overwritten."
  (:require [clojure.string :as str]
            [hive-build.promote.notes :as notes]))

(def Release
  [:map {:closed true}
   [:release/version :string]
   [:release/date [:maybe :string]]
   [:release/prose [:maybe :string]]
   [:release/note notes/Note]])

(def Changelog
  [:map {:closed true}
   [:changelog/preamble [:maybe :string]]
   [:changelog/footer [:maybe :string]]
   ;; :gen/max bounds GENERATION only, never validation: a real changelog holds
   ;; as many releases as it holds, but generating unbounded documents of
   ;; unbounded notes exhausts the heap before it tests anything.
   [:changelog/releases [:sequential {:gen/max 3} Release]]])

(def default-preamble
  "The header of a generated changelog: what the file is, and where to author
   what it cannot derive."
  (str "# Changelog\n"
       "\n"
       "Notable changes, derived from the conventional-commit history between\n"
       "release tags. Format follows [Keep a Changelog](https://keepachangelog.com/en/1.1.0/);\n"
       "versioning follows [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n"
       "\n"
       "This file is GENERATED by `clojure -T:build changelog`. Do not edit it:\n"
       "prose for a release belongs in `changelog.d/<version>.md`, which is\n"
       "spliced in below its heading and is never overwritten.\n"))

(defn entry-line
  "One note entry as a list item. A scoped commit keeps its scope as the lead."
  [{:note/keys [scope summary]}]
  (if (str/blank? (str scope))
    (str "- " summary)
    (str "- **" scope ":** " summary)))

(defn section-block
  "One published kind as a markdown section, or nil when it has no entries."
  [{:section/keys [heading entries]}]
  (when (seq entries)
    (str "### " heading "\n\n"
         (str/join "\n" (map entry-line entries)) "\n")))

(defn breaking-block
  "Every breaking change, above the sections, or nil when there are none.

   Lifted out of its own kind on purpose: a reader deciding whether to take
   this version has one question that outranks what else arrived with it."
  [entries]
  (when (seq entries)
    (str "### BREAKING\n\n"
         (str/join "\n" (map entry-line entries)) "\n")))

(defn routine-line
  "The housekeeping this release also carried, as one sentence, or nil.

   Reported rather than dropped so a release that is entirely dependency bumps
   reads as one instead of as an empty release. The counts add with `+'`: they
   are unbounded in the schema, and a renderer must not throw on a number it
   was handed."
  [{:note/keys [routine unconventional]}]
  (let [total (+' (or routine 0) (or unconventional 0))]
    (when (pos? total)
      (str "_Plus " total " routine commit" (when (not= 1 total) "s")
           " (docs, tests, build, chores)._\n"))))

(defn release-block
  "One release: its heading, its authored prose, then what git says.

   Every part ends in a newline so the join leaves a blank line between them,
   which is what makes them separate markdown blocks rather than one run-on
   paragraph."
  [{:release/keys [version date prose note]}]
  (let [heading (str "## [" version "]" (when (seq (str date)) (str " - " date)))
        parts (keep identity
                    (concat [(when (seq (str prose)) (str (str/trim (str prose)) "\n"))
                             (breaking-block (:note/breaking note))]
                            (map section-block (:note/sections note))
                            [(when-not (notes/newsworthy? note)
                               "_No user-facing changes._\n")
                             (routine-line note)]))]
    (str heading "\n\n" (str/join "\n" parts))))

(defn render
  "The whole document, newest release first.

   A changelog with no releases still renders its preamble: a repository that
   has never tagged has an honest empty changelog, not a missing one. The
   footer carries whatever the render had to leave out."
  [{:changelog/keys [preamble footer releases]}]
  (let [head (or (not-empty (str/trim (str preamble))) default-preamble)
        body (str/join "\n" (map release-block releases))
        tail (when (seq (str/trim (str footer))) (str/trim (str footer)))]
    (str (str/trim head) "\n\n"
         body
         (when tail (str "\n" tail "\n")))))
